- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Add Google official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        mode: 0600

    - name: Installing Kubernetes Cluster Packages
      apt: name={{ item }} state=present
      loop:
        - kubeadm
        - kubectl
        - kubelet

    - name: Hold kubeadm
      become: yes
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Hold kubectl
      become: yes
      dpkg_selections:
        name: kubectl
        selection: hold

    - name: Hold kubelet
      become: yes
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: Add line Net Bridge on sysctl.conf
      become: yes
      lineinfile:
        path: /etc/sysctl.conf
        line: net.bridge.bridge-nf-call-iptables=1

    - name: Add line 'max_map_count' on sysctl.conf
      become: yes
      lineinfile:
        path: /etc/sysctl.conf
        line: vm.max_map_count=262144

    - name: Apply change on sysctl
      become: yes
      become_method: sudo
      shell: sysctl -p

    - name: Disable Swapp
      become_method: sudo
      shell: swapoff -a

- hosts: master
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Initialize k8s Cluster
      become: yes
      become_method: sudo
      shell: kubeadm --v=5 init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_result

    - debug:
        var: kubeadm_result.stdout_lines

    - name: Make configuration folder for k8s
      become: yes
      become_user: ubuntu
      file:
        state: directory
        path: /home/ubuntu/.kube
        mode: 0755

    - name: Copy configuration k8s into home
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Get the token for joining the worker nodes
      become: yes 
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- hosts: workers
  remote_user: ubuntu
  gather_facts: false

  tasks:
   - name: Copy join command from Ansiblehost to the worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not

